version: '3.8'

services:

  redis:
    image: redis:7.0.11-alpine

  django:
    container_name: django
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/www
    ports:
      - 8001:8000
    environment:
      - DEBUG=1
      - SECRET_KEY = 0930jd30j9jd09
      - ALLOWED_HOSTS=localhost, 127.0.0.1
    depends_on:
      - redis
  
  celery:
    container_name: celery
    build:
      context: .
    command: celery --app=djangocelery worker -l INFO
    volumes:
      - .:/www
    environment:
      - DEBUG=1
      - SECRET_KEY = 0930jd30j9jd09
      - ALLOWED_HOSTS=localhost, 127.0.0.1
    depends_on:
      - redis